// TODO constant types
export const SHOW_ALL = "SHOW_ALL";
export const TOGGLE_VISIBILITY_ADD_MODAL = "TOGGLE_VISIBILITY_ADD_MODAL";
export const ADD_TODO = "ADD_TODO";
export const FINISHED_TODO = "FINISHED_TODO";
export const UNFINISHED_TODO = "UNFINISHED_TODO";
export const GET_SHOWED_TODO = "GET_SHOWED_TODO";
export const SET_FOCUSED_TODO = "SET_FOCUSED_TODO";
export const REMOVED_TODO = "REMOVED_TODO";
export const INCREMENT_FOCUCED_TIME = "INCREMENT_FOCUCED_TIME";

// PROMODORO constant types
export const DECREMENT_BREACK = "DECREMENT_BREACK";
export const DECREMENT_PROMODORO = "DECREMENT_PROMODORO";
export const INCREMENT_PROMODORO_ROUND = "INCREMENT_PROMODORO_ROUND";
export const INCREMENT_BREACK_ROUND = "INCREMENT_BREACK_ROUND";
export const SET_PROMODOORO_STATUS = "SET_PROMODOORO_STATUS";
export const SET_PLAY_STATUS = "SET_PLAY_STATUS";
export const SET_PROMODO_TIME = "SET_PROMODO_TIME";
export const SET_BREAK_TIME = "SET_BREAK_TIME";
export const SET_PROMODO_ROUND = "SET_PROMODO_ROUND";
export const SET_BREAK_ROUND = "SET_BREAK_ROUND";
